### PR TITLE
Fix for #342

### LINKED ISSUE #342: Support for arbitrary javascript dialects
As of now, vows supports both standard Javascript and CoffeeScript.

How about adding support for arbitrary Javascript "dialects" and provably also other languages that can be run inside the node environment or for which at least a parser/compiler can be registered for with node's require function?

grunt are using [tkellen/node-rechoir](/tkellen/node-rechoir) for this.

I think that this would be of value for vows as well...

### PR DESCRIPTION
**Pull request by silkentrance**
- fixes #342: now supporting arbitrary javascript dialects instead of just coffee-script

### CODE REVIEW

**Comment by indexzero** [comment]
Sorry for the delay. I'd like to see a test for this.

**Comment by silkentrance** [comment]
@indexzero 
I have discontinued using vows in favor of mocha as I am transitioning to babel/ES. If you need further work done on this, please suit yourself.

I also have no longer need for my clone containing the branch on which this PR is based upon. I can transfer this clone to you, if you want. So drop me a note.

**Comment by indexzero** [comment]
Github will keep the PR around.

**Comment by silkentrance** [comment]
Great, will delete my fork then.

**Pull request closed without merging**
