### PR TITLE
Fix for #350

### LINKED ISSUE #350: vows-test.js/CrazyEmitter tests are not implemented and will fail when implementing them
While working on #349 I stumbled across some test cases not being implemented in test/vows-test.js.

These test cases deal with a synchronous emitter test that will listen on custom events of the emitter. When implementing these tests I found that they will always fail as the emitter will be passed to the vow instead of the data emitted by the event upon which that vow was listening as its topics.

It turned out that in lib/vows/addVows the last success event arguments would always be used instead of the vow.binding.context.nextTopics() when calling runTest(...).

Quite a bugger, that one.

See the follow up PR for a fix for that issue.

### PR DESCRIPTION
**Pull request by silkentrance**
- fixes #350: erroneous arguments were passed to test cases causing event emitter tests to fail

### CODE REVIEW

**Comment by silkentrance** [comment]
@indexzero Any progress on this?

**Comment by indexzero** [comment]
This is also breaking. I'd like to get a stable `0.9.x` out before merging.

**Comment by silkentrance** [comment]
@indexzero 
I have discontinued using vows in favor of mocha as I am transitioning to babel/ES. If you need further work done on this, please suit yourself.

I also have no longer need for my clone containing the branch on which this PR is based upon. I can transfer this clone to you, if you want. So drop me a note.

**Comment by indexzero** [comment]
Github will keep the PR around.

**Comment by silkentrance** [comment]
Great, will delete my fork then.

**Pull request closed without merging**
