### PR TITLE
Add `this.callback` alternative w/o error argument

### PR DESCRIPTION
**Pull request by moteutsch**
Added a function `this.callbackWithoutError` in addition to `this.callback`. This will be used on a case-by-case basis when `topic` is asynchronous and result callback doesn't pass error as first parameter, instead passing the result (to be passed to a vow).

### CODE REVIEW

**Comment by silkentrance** [comment]
@indexzero

Actually, I am having a hard time understanding the issue in the first place. Not so much the asynchronous part, just the special casing that this would introduce into the otherwise clean api.

And, considering the provided examples over at vowsjs.org dealing with asynchronous testing,
is missing the point. Why introduce an additional method if you can always also pass null as the first parameter? See here

```
exports.Banana.prototype = {
    peel: function (callback) {
        process.nextTick(function () {
            callback(null, new(exports.PeeledBanana));
        });
    },
    peelSync: function () { return new(exports.PeeledBanana) }
};

and later on

        'when peeled *asynchronously*': {
            topic: function (banana) {
                banana.peel(this.callback);
            },
            'results in a `PeeledBanana`': function (err, result) {
                assert.instanceOf (result, PeeledBanana);
            }
        }
```

I believe that a minority of APIs will actually work this way, not passing the error as first parameter to the callback, something which has been established long ago in the node apis. If the OP wants to support their own apis which do digress from the established pattern, then they should be using a wrapper, e.g.

```
            topic: function (banana) {
                var self = this;
                banana.peel(function (result) {self.callback(null, result);});
            },
```

I'd say, ignore and close as this is more about special casing APIs that do not conform to the best practices that have already been established.

**Comment by silkentrance** [comment]
A provable other fix for this would be to examine the arguments passed to the callback in the line of `!(arguments[0] instanceof Error)` would then cause the callback to ignore the non existing error...

**Comment by silkentrance** [comment]
Besides of that, there already exists a special case for a return result of type boolean.

**Comment by moteutsch** [comment]
Personally, I stopped using vows because I found it was too inflexible. A
testing framework should not impose style guidelines on the production
code, but rather facilitate testing!

**Comment by LukeGT** [comment]
@moteutsch +1

**Comment by indexzero** [comment]
@moteutsch could you elaborate on what you mean by "impose style guidelines on the production code"?

**Comment by moteutsch** [comment]
My remark was made in response to Carsten Klien's position to my patch.

**Comment by indexzero** [comment]
@moteutsch roger. I hadn't read up. Error handling is the most important issue for the `vows` project right now. I will distill a decision soon.

**Comment by soletan** [comment]
Stumbled over vows in general and over undocumented (mis)behaviour of this.callback in particular. 

Why is `this.callback` bound to nodejs callback signature? Why isn't that documented on website? As a newbie with vows it took me quite too much time to figure out what is going wrong. While I'm struggling with the structure of vows test descriptions I carefully check to have test descriptions complying with any documentation I get. This takes times ... so please: if {{this.callback}} is designed to implicitly consider any object passed as first argument being an error description making any test fail, _you should definitely provide that anything but minor information to the users._ It takes so little to do that.

Tried this:

```
vows.describe( "case" )
	.addBatch( {
		"testing callback once": {
			topic: function() { this.callback( true ); },
			"is succeeding": function( data ) {
				// this case is NOT failing
				assert.isTrue( data );
			}
		},
		"testing callback again": {
			topic: function() { this.callback( { info: true } ); },
			"is succeeding": function( data ) {
				// this case is unexpectedly failing
				assert.isTrue( data.info );
			}
		}
	} );
```

**Comment by soletan** [comment]
@silkentrance 

> I'd say, ignore and close as this is more about special casing APIs that do not conform to the best practices that have already been established.

It's quite a complete different story talking about what is required to become "the _best_ practices". I personally prefer promises over using chains of callbacks. IMHO promises come with benefits over NodeJS-style callbacks regarding to code readability. That's another personal opinion. A testing framework shouldn't stick with one of them but try to support either one as broadly as possible, focusing on its basic intention of enabling users to write tests quite as simple as writing code to be tested.

**Comment by silkentrance** [comment]
@soletan True, I also very much like the promise based approach. However, this would require an entire rewrite of vows... Which might be a good thing now that promises and other asynchronous APIs become more and more the standard.

**Comment by soletan** [comment]
Dismissed. Nevertheless, as mentioned before by @luke-tsekouras-sirca, the doc isn't stating this tight relation to NodeJS-style callbacks and for a newbie in using vows it might prevent some headache to find a note over there, for `this.callback` isn't _**just** passing_ arguments, but processing them. So here is my +1 on this issue.

**Pull request closed without merging**
